spring:
  datasource:
    url: jdbc:h2:mem:game-db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      use-new-id-generator-mappings: false
    show-sql: true