version: 0.2

env:
  parameter-store:
    COVERALLS_TOKEN: "/trak-api/coveralls-token"

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo [INFO] Cleaning Trak API `date`
      - mvn clean
  build:
    commands:
      - echo [INFO] Building Trak API `date`
      - mvn compile
  post_build:
    commands:
      - echo [INFO] Running Trak API tests `date`
      - mvn test jacoco:report coveralls:report -DrepoToken=$COVERALLS_TOKEN
      - echo [INFO] Packaging Trak API `date`
      - mvn package -DskipTests

artifacts:
  files:
    - auth-server/target/auth-server-1.0-SNAPSHOT.jar
    - config-server/target/config-server-1.0-SNAPSHOT.jar
    - discovery-server/target/discovery-server-1.0-SNAPSHOT.jar
    - email-server/target/email-server-1.0-SNAPSHOT.jar
    - game-server/target/game-server-1.0-SNAPSHOT.jar
    - gateway-server/target/gateway-server-1.0-SNAPSHOT.jar
    - image-server/target/image-server-1.0-SNAPSHOT.jar
  discard-paths: yes
