version: 0.2

env:
  shell: bash
  parameter-store:
    SONAR_TOKEN: "/trak-api/sonarcloud-token"

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo [INFO] Cleaning Trak API `date`
      - mvn clean -Pcoverage
  build:
    commands:
      - echo [INFO] Building Trak API `date`
      - mvn compile -Pcoverage
  post_build:
    commands:
      - echo [INFO] Running Trak API tests `date`
      - |
        branch_name=$CODEBUILD_SOURCE_VERSION
        if [[ "$branch_name" == pr/* ]] ;
        then
        	pull_request_number="${branch_name:3}"
        	mvn verify sonar:sonar -Pcoverage -Dsonar.pullrequest.provider=Github -Dsonar.pullrequest.github.repository=sparky-studios/trak-api -Dsonar.pullrequest.key=$pull_request_number -Dsonar.pullrequest.branch=$CODEBUILD_WEBHOOK_HEAD_REF
        else
        	mvn verify sonar:sonar -Pcoverage -Dsonar.branch.name=develop
        fi
      - echo [INFO] Packaging Trak API `date`
      - mvn package -DskipTests

artifacts:
  files:
    - auth-server/target/auth-server-1.0-SNAPSHOT.jar
    - config-server/target/config-server-1.0-SNAPSHOT.jar
    - discovery-server/target/discovery-server-1.0-SNAPSHOT.jar
    - email-server/target/email-server-1.0-SNAPSHOT.jar
    - game-server/target/game-server-1.0-SNAPSHOT.jar
    - gateway-server/target/gateway-server-1.0-SNAPSHOT.jar
    - image-server/target/image-server-1.0-SNAPSHOT.jar
    - notification-server/target/notification-server-1.0-SNAPSHOT.jar
  discard-paths: yes
