version: '3.3'
services:
  auth-server:
    environment:
      - spring.profiles.active=staging
  config-server:
    environment:
      - spring.profiles.active=staging

  discovery-server:
    environment:
      - spring.profiles.active=staging

  email-server:
    environment:
      - spring.profiles.active=staging

  game-server:
    environment:
      - spring.profiles.active=staging

  gateway-server:
    environment:
      - spring.profiles.active=staging

  image-server:
    environment:
      - spring.profiles.active=staging

  notification-server:
    environment:
      - spring.profiles.active=staging
