version: "3.3"
services:
  auth-server:
    container_name: traklibrary-auth-server
    command: ["-m", "512m"]
    environment:
      - spring.cloud.config.username=${CONFIG_SERVER_SECURITY_USERNAME}
      - spring.cloud.config.password=${CONFIG_SERVER_SECURITY_PASSWORD}
    depends_on:
      - discovery-server
      - config-server
    restart: on-failure
    networks:
      - trak-network

  config-server:
    container_name: traklibrary-config-server
    command: ["-m", "512m"]
    environment:
      - spring.cloud.config.server.git.password=${CONFIG_SERVER_GIT_PASSWORD}
      - spring.cloud.config.server.git.username=${CONFIG_SERVER_GIT_USERNAME}
      - spring.security.user.name=${CONFIG_SERVER_SECURITY_USERNAME}
      - spring.security.user.password=${CONFIG_SERVER_SECURITY_PASSWORD}
    depends_on:
      - discovery-server
    restart: on-failure
    networks:
      - trak-network

  discovery-server:
    container_name: traklibrary-discovery-server
    command: ["-m", "512m"]
    networks:
      - trak-network

  email-server:
    container_name: traklibrary-email-server
    command: ["-m", "512m"]
    environment:
      - spring.cloud.config.username=${CONFIG_SERVER_SECURITY_USERNAME}
      - spring.cloud.config.password=${CONFIG_SERVER_SECURITY_PASSWORD}
    depends_on:
      - discovery-server
      - config-server
    restart: on-failure
    networks:
      - trak-network

  game-server:
    container_name: traklibrary-game-server
    command: ["-m", "512m"]
    environment:
      - spring.cloud.config.username=${CONFIG_SERVER_SECURITY_USERNAME}
      - spring.cloud.config.password=${CONFIG_SERVER_SECURITY_PASSWORD}
    depends_on:
      - discovery-server
      - config-server
    restart: on-failure
    networks:
      - trak-network

  gateway-server:
    container_name: traklibrary-gateway-server
    command: ["-m", "512m"]
    environment:
      - spring.cloud.config.username=${CONFIG_SERVER_SECURITY_USERNAME}
      - spring.cloud.config.password=${CONFIG_SERVER_SECURITY_PASSWORD}
    depends_on:
      - discovery-server
      - config-server
    restart: on-failure
    networks:
      - trak-network

  image-server:
    container_name: traklibrary-image-server
    command: ["-m", "512m"]
    environment:
      - spring.cloud.config.username=${CONFIG_SERVER_SECURITY_USERNAME}
      - spring.cloud.config.password=${CONFIG_SERVER_SECURITY_PASSWORD}
    depends_on:
      - discovery-server
      - config-server
    restart: on-failure
    networks:
      - trak-network

  notification-server:
    container_name: traklibrary-notification-server
    command: ["-m", "512m"]
    environment:
      - spring.cloud.config.username=${CONFIG_SERVER_SECURITY_USERNAME}
      - spring.cloud.config.password=${CONFIG_SERVER_SECURITY_PASSWORD}
    depends_on:
      - discovery-server
      - config-server
    restart: on-failure
    networks:
      - trak-network

networks:
  trak-network:
    driver: bridge
