version: '3.3'
services:
  db:
    container_name: traklibrary-db
    image: postgres:13.2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - trak-db-data:/var/lib/postgresql/data
      - ./scripts/db:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432
    networks:
      - trak-network

  auth-server:
    build:
      context: ./auth-server
    volumes:
      - ./logs:/app/logs
    environment:
      - spring.profiles.active=development
      - spring.cloud.config.profile=development
    depends_on:
      - db
      - discovery-server
      - config-server
    ports:
      - 5005:5005

  config-server:
    build:
      context: ./config-server
    volumes:
      - ./logs:/app/logs
    environment:
      - spring.profiles.active=development
      - spring.cloud.config.profile=development
    ports:
      - 5006:5005

  discovery-server:
    build:
      context: ./discovery-server
    volumes:
      - ./logs:/app/logs
    environment:
      - spring.profiles.active=development
      - spring.cloud.config.profile=development
    ports:
      - 5007:5005

  email-server:
    build:
      context: ./email-server
    volumes:
      - ./logs:/app/logs
    environment:
      - spring.profiles.active=development
      - spring.cloud.config.profile=development
    ports:
      - 5008:5005

  game-server:
    build:
      context: ./game-server
    volumes:
      - ./logs:/app/logs
    environment:
      - spring.profiles.active=development
      - spring.cloud.config.profile=development
    depends_on:
      - db
      - discovery-server
      - config-server
    ports:
      - 5009:5005

  gateway-server:
    build:
      context: ./gateway-server
    volumes:
      - ./logs:/app/logs
    environment:
      - spring.profiles.active=development
      - spring.cloud.config.profile=development
    ports:
      - 5010:5005

  image-server:
    build:
      context: ./image-server
    volumes:
      - ./logs:/app/logs
    environment:
      - spring.profiles.active=development
      - spring.cloud.config.profile=development
    ports:
      - 5011:5005

  notification-server:
    build:
      context: ./notification-server
    volumes:
      - ./logs:/app/logs
    environment:
      - spring.profiles.active=development
      - spring.cloud.config.profile=development
    depends_on:
      - db
      - discovery-server
      - config-server
    ports:
      - 5012:5005

volumes:
  trak-db-data: