version: "3.3"
services:
  auth-server:
    container_name: traklibrary-auth-server
    image: sparkystudios/traklibrary-auth-server:${VERSION}
    command: ["-m", "512m", "-XX:MinRAMPercentage=50", "-XX:MaxRAMPercentage=80"]
    environment:
      - encrypt.key=${CONFIG_SERVER_ENCRYPT_KEY}
      - spring.cloud.bootstrap.enabled=true
      - spring.cloud.config.username=${CONFIG_SERVER_SECURITY_USERNAME}
      - spring.cloud.config.password=${CONFIG_SERVER_SECURITY_PASSWORD}
      - spring.cloud.discovery.username=${DISCOVERY_SERVER_USERNAME}
      - spring.cloud.discovery.password=${DISCOVERY_SERVER_PASSWORD}
    depends_on:
      - discovery-server
      - config-server
    restart: on-failure
    expose:
      - 8080
    networks:
      - trak-network

  config-server:
    container_name: traklibrary-config-server
    image: sparkystudios/traklibrary-config-server:${VERSION}
    command: ["-m", "512m", "-XX:MinRAMPercentage=50", "-XX:MaxRAMPercentage=80"]
    environment:
      - encrypt.key=${CONFIG_SERVER_ENCRYPT_KEY}
      - spring.cloud.config.server.git.password=${CONFIG_SERVER_GIT_PASSWORD}
      - spring.cloud.config.server.git.username=${CONFIG_SERVER_GIT_USERNAME}
      - spring.security.user.name=${CONFIG_SERVER_SECURITY_USERNAME}
      - spring.security.user.password=${CONFIG_SERVER_SECURITY_PASSWORD}
      - spring.cloud.discovery.username=${DISCOVERY_SERVER_USERNAME}
      - spring.cloud.discovery.password=${DISCOVERY_SERVER_PASSWORD}
    depends_on:
      - discovery-server
    expose:
      - 8888
    restart: on-failure
    networks:
      - trak-network

  discovery-server:
    container_name: traklibrary-discovery-server
    image: sparkystudios/traklibrary-discovery-server:${VERSION}
    command: ["-m", "512m", "-XX:MinRAMPercentage=50", "-XX:MaxRAMPercentage=80"]
    environment:
      - spring.security.user.name=${DISCOVERY_SERVER_USERNAME}
      - spring.security.user.password=${DISCOVERY_SERVER_PASSWORD}
    ports:
    - 8761:8761
    networks:
      - trak-network

  email-server:
    container_name: traklibrary-email-server
    image: sparkystudios/traklibrary-email-server:${VERSION}
    command: ["-m", "512m", "-XX:MinRAMPercentage=50", "-XX:MaxRAMPercentage=80"]
    environment:
      - encrypt.key=${CONFIG_SERVER_ENCRYPT_KEY}
      - spring.cloud.bootstrap.enabled=true
      - spring.cloud.config.username=${CONFIG_SERVER_SECURITY_USERNAME}
      - spring.cloud.config.password=${CONFIG_SERVER_SECURITY_PASSWORD}
      - spring.cloud.discovery.username=${DISCOVERY_SERVER_USERNAME}
      - spring.cloud.discovery.password=${DISCOVERY_SERVER_PASSWORD}
    depends_on:
      - discovery-server
      - config-server
    expose:
      - 8080
    restart: on-failure
    networks:
      - trak-network

  game-server:
    container_name: traklibrary-game-server
    image: sparkystudios/traklibrary-game-server:${VERSION}
    command: ["-m", "512m", "-XX:MinRAMPercentage=50", "-XX:MaxRAMPercentage=80"]
    environment:
      - encrypt.key=${CONFIG_SERVER_ENCRYPT_KEY}
      - spring.cloud.bootstrap.enabled=true
      - spring.cloud.config.username=${CONFIG_SERVER_SECURITY_USERNAME}
      - spring.cloud.config.password=${CONFIG_SERVER_SECURITY_PASSWORD}
      - spring.cloud.discovery.username=${DISCOVERY_SERVER_USERNAME}
      - spring.cloud.discovery.password=${DISCOVERY_SERVER_PASSWORD}
    depends_on:
      - discovery-server
      - config-server
    expose:
      - 8080
    restart: on-failure
    networks:
      - trak-network

  gateway-server:
    container_name: traklibrary-gateway-server
    image: sparkystudios/traklibrary-gateway-server:${VERSION}
    command: ["-m", "512m", "-XX:MinRAMPercentage=50", "-XX:MaxRAMPercentage=80"]
    environment:
      - encrypt.key=${CONFIG_SERVER_ENCRYPT_KEY}
      - spring.cloud.bootstrap.enabled=true
      - spring.cloud.config.username=${CONFIG_SERVER_SECURITY_USERNAME}
      - spring.cloud.config.password=${CONFIG_SERVER_SECURITY_PASSWORD}
      - spring.cloud.discovery.username=${DISCOVERY_SERVER_USERNAME}
      - spring.cloud.discovery.password=${DISCOVERY_SERVER_PASSWORD}
    depends_on:
      - discovery-server
      - config-server
    expose:
      - 8080
    ports:
    - 8080:8080
    restart: on-failure
    networks:
      - trak-network

  image-server:
    container_name: traklibrary-image-server
    image: sparkystudios/traklibrary-image-server:${VERSION}
    command: ["-m", "512m", "-XX:MinRAMPercentage=50", "-XX:MaxRAMPercentage=80"]
    environment:
      - encrypt.key=${CONFIG_SERVER_ENCRYPT_KEY}
      - spring.cloud.bootstrap.enabled=true
      - spring.cloud.config.username=${CONFIG_SERVER_SECURITY_USERNAME}
      - spring.cloud.config.password=${CONFIG_SERVER_SECURITY_PASSWORD}
      - spring.cloud.discovery.username=${DISCOVERY_SERVER_USERNAME}
      - spring.cloud.discovery.password=${DISCOVERY_SERVER_PASSWORD}
    depends_on:
      - discovery-server
      - config-server
    expose:
      - 8080
    restart: on-failure
    networks:
      - trak-network

  notification-server:
    container_name: traklibrary-notification-server
    image: sparkystudios/traklibrary-notification-server:${VERSION}
    command: ["-m", "512m", "-XX:MinRAMPercentage=50", "-XX:MaxRAMPercentage=80"]
    environment:
      - encrypt.key=${CONFIG_SERVER_ENCRYPT_KEY}
      - spring.cloud.bootstrap.enabled=true
      - spring.cloud.config.username=${CONFIG_SERVER_SECURITY_USERNAME}
      - spring.cloud.config.password=${CONFIG_SERVER_SECURITY_PASSWORD}
      - spring.cloud.discovery.username=${DISCOVERY_SERVER_USERNAME}
      - spring.cloud.discovery.password=${DISCOVERY_SERVER_PASSWORD}
    depends_on:
      - discovery-server
      - config-server
    expose:
      - 8080
    restart: on-failure
    networks:
      - trak-network

networks:
  trak-network:
    driver: bridge
