server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaulZone: http://${spring.security.user.name}:${spring.security.user.password}@localhost:8761/eureka
spring:
  application:
    name: trak-discovery-server
