eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

spring:
  application:
    name: trak-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/TheLordBritish/trak-api-properties.git

server:
  port: 8888