eureka:
  client:
    service-url:
      defaultZone: http://${spring.cloud.discovery.username}:${spring.cloud.discovery.password}@discovery-server:8761/eureka

spring:
  application:
    name: trak-config-server
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/TheLordBritish/trak-api-properties.git

server:
  port: 8888